### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Vardanos** [jacklin18/DeepGS#1]
Hello

In the script run_training_DeepGS.py on line 323:

    with open('../dataset/' + DATASET + '/smile_n_gram.txt', 'r') as f:

        smile = f.read().strip().split('\n')

I couldn't find this file (smile_n_gram.txt) in the codebase

Thanks in advance

**Comment by XuanLin1991** [comment]
@Vardanos Hello,

Thank you for your interest. You can find this file in dataset/smile_n_gram.txt.

**Comment by XuanLin1991** [comment]
Closing for now. Please feel free to open a new issue if you have any other questions.
