### ISSUE TITLE
Data problems

### ISSUE THREAD

**Issue by Vardanos** [jacklin18/DeepGS#2]
Hello,

I have a couple more issues and questions with running the code
1. input.txt file contains duplicates, it seems like there are only 49 original smiles in the dataset, is this normal?
2. There seem to be problems with dataset creation and splitting methods on line 360-364 run_training_DeepGS.py

Thanks in advance

**Comment by thiagobrs** [comment]
Hello Lin Xuan,

I think that I'm facing the same problem as Vardanos. Please, could you give us some piece of advice?

Thanks,

Thiago Batista

**Comment by XuanLin1991** [comment]
Hi, thank you for your interest. The input.txt file is originally derived from [DeepDTA](https://github.com/hkmztrk/DeepDTA), and we reconstructed the input data for the requirement of DeepGS model. Specifically, we excluded data contains '.' in the SMILES format while only 68 ligands in the original Davis dataset.

**Comment by XuanLin1991** [comment]
> 
> 
> Hello,
> 
> I have a couple more issues and questions with running the code
> 
>     1. input.txt file contains duplicates, it seems like there are only 49 original smiles in the dataset, is this normal?
> 
>     2. There seem to be problems with dataset creation and splitting methods on line 360-364 run_training_DeepGS.py
> 
> 
> Thanks in advance

Hi,  as for the original 68 ligands in Davis dataset, for example, you can obtain the valid 68 SMILES by using preprocessing such as  [standardization](http://www.rdkit.org/docs/source/rdkit.Chem.MolStandardize.rdMolStandardize.html) and [canonicalization](https://www.rdkit.org/docs/GettingStartedInPython.html).

**Comment by thiagobrs** [comment]
Hi Lin,

Thank you for the reply!!! I'm going to try again following the tips you
gave.

Att.,

Thiago Batista

Em sex., 17 de jul. de 2020 às 02:05, Lin Xuan <notifications@github.com>
escreveu:
