### ISSUE TITLE
generate smile_n_gram.txt

### ISSUE THREAD

**Issue by nirku** [jacklin18/DeepGS#3]
Hi, 
Can you please explain how you generated the file smile_n_gram.txt
I only see a multiple smiles repeating themselves with space between characters.

Thank you,

**Comment by XuanLin1991** [comment]
@nirku Sorry, I did not reply to you in time. This file is just processing to form drug-target pairs.

Best regards,
Xuan

**Comment by jacklin18** [comment]
Closing for now. Please feel free to open a new issue if you have any other questions.
